codecov:
  notify:
    after_n_builds: 1

coverage:
  status:
    project: off
    patch: off
    changes:
      default:
        target: 80%
<<<<<<< HEAD
        if_not_found: success
=======
        if_not_found: success
>>>>>>> feat(repo-setup): bootstrap dev environment and repo setup
