version: 2.1
machine:
  environment:
    PATH: '${PATH}:${HOME}/${CIRCLE_PROJECT_REPONAME}/node_modules/.bin'
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:14.15
  resource_class: large

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: yarn config set workspaces-experimental true
      - run: yarn cache clean --force
      - run: yarn run production-build
      - save_cache:
          key: amplify-codegen-yarn-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.cache
      - save_cache:
          key: amplify-codegen-ssh-deps-{{ .Branch }}
          paths:
            - ~/.ssh
      - persist_to_workspace:
          root: .
          paths: .

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ./
      - restore_cache:
          key: amplify-codegen-yarn-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Update OS Packages
          command: sudo apt-get update
      - run:
          name: Install Java
          command: |
            curl -O https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_linux-x64_bin.tar.gz
            tar zxvf openjdk-11.0.2_linux-x64_bin.tar.gz
            sudo mv jdk-11* /usr/local/
            echo "export JAVA_HOME=/usr/local/jdk-11.0.2" >> $BASH_ENV
            echo "export PATH=$PATH:/usr/local/jdk-11.0.2/bin" >> $BASH_ENV
            source $BASH_ENV
            java -version
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Run tests
          command: yarn test-ci
      - run:
          name: Collect code coverage
          command: yarn coverage

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ./
      - restore_cache:
          keys:
            - amplify-codegen-ssh-deps-{{ .Branch }}
            - amplify-codegen-yarn-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Authenticate with npm
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          name: Publish Amplify Codegen
          command: |
            if [ -z "$CIRCLE_PULL_REQUEST" ]; then
              git config --global user.email $GITHUB_EMAIL
              git config --global user.name $GITHUB_USER
              npm run publish:$CIRCLE_BRANCH
            else
              echo "Skipping deploy."
            fi

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
            - test
          filters:
            branches:
              only:
                # - release
                - master
